CREATE TABLE contacts (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  phone VARCHAR(20),
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
